//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetCmdOutput.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SdtBackup", Namespace="CS3HQ")]
    [System.SerializableAttribute()]
    public partial class SdtBackup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClieCodField;
        
        private string ProdCodField;
        
        private string BckNomField;
        
        private bool BckEstField;
        
        private string BckMsgField;
        
        private long BckTamField;
        
        private string BckGitRemoteField;
        
        private string BckGitCommitField;
        
        private string BckGitBranchField;
        
        private string BckLastReorgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ClieCod {
            get {
                return this.ClieCodField;
            }
            set {
                if ((object.ReferenceEquals(this.ClieCodField, value) != true)) {
                    this.ClieCodField = value;
                    this.RaisePropertyChanged("ClieCod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ProdCod {
            get {
                return this.ProdCodField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdCodField, value) != true)) {
                    this.ProdCodField = value;
                    this.RaisePropertyChanged("ProdCod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string BckNom {
            get {
                return this.BckNomField;
            }
            set {
                if ((object.ReferenceEquals(this.BckNomField, value) != true)) {
                    this.BckNomField = value;
                    this.RaisePropertyChanged("BckNom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool BckEst {
            get {
                return this.BckEstField;
            }
            set {
                if ((this.BckEstField.Equals(value) != true)) {
                    this.BckEstField = value;
                    this.RaisePropertyChanged("BckEst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string BckMsg {
            get {
                return this.BckMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.BckMsgField, value) != true)) {
                    this.BckMsgField = value;
                    this.RaisePropertyChanged("BckMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public long BckTam {
            get {
                return this.BckTamField;
            }
            set {
                if ((this.BckTamField.Equals(value) != true)) {
                    this.BckTamField = value;
                    this.RaisePropertyChanged("BckTam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string BckGitRemote {
            get {
                return this.BckGitRemoteField;
            }
            set {
                if ((object.ReferenceEquals(this.BckGitRemoteField, value) != true)) {
                    this.BckGitRemoteField = value;
                    this.RaisePropertyChanged("BckGitRemote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string BckGitCommit {
            get {
                return this.BckGitCommitField;
            }
            set {
                if ((object.ReferenceEquals(this.BckGitCommitField, value) != true)) {
                    this.BckGitCommitField = value;
                    this.RaisePropertyChanged("BckGitCommit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=8)]
        public string BckGitBranch {
            get {
                return this.BckGitBranchField;
            }
            set {
                if ((object.ReferenceEquals(this.BckGitBranchField, value) != true)) {
                    this.BckGitBranchField = value;
                    this.RaisePropertyChanged("BckGitBranch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=9)]
        public string BckLastReorg {
            get {
                return this.BckLastReorgField;
            }
            set {
                if ((object.ReferenceEquals(this.BckLastReorgField, value) != true)) {
                    this.BckLastReorgField = value;
                    this.RaisePropertyChanged("BckLastReorg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="HQ.Backups.WsNotificacionBackupSoapPort", Namespace="CS3HQ", ConfigurationName="ServiceReference1.HQBackupsWsNotificacionBackupSoapPort")]
    public interface HQBackupsWsNotificacionBackupSoapPort {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (HQ.Backups.WsNotificacionBackup.Execute) del mensaje ExecuteRequest no coincide con el valor predeterminado (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="CS3HQaction/hq.backups.AWSNOTIFICACIONBACKUP.Execute", ReplyAction="*")]
        GetCmdOutput.ServiceReference1.ExecuteResponse Execute(GetCmdOutput.ServiceReference1.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HQ.Backups.WsNotificacionBackup.Execute", WrapperNamespace="CS3HQ", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS3HQ", Order=0)]
        public GetCmdOutput.ServiceReference1.SdtBackup Sdtbackup;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(GetCmdOutput.ServiceReference1.SdtBackup Sdtbackup) {
            this.Sdtbackup = Sdtbackup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HQ.Backups.WsNotificacionBackup.ExecuteResponse", WrapperNamespace="CS3HQ", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS3HQ", Order=0)]
        public string retval;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(string retval) {
            this.retval = retval;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HQBackupsWsNotificacionBackupSoapPortChannel : GetCmdOutput.ServiceReference1.HQBackupsWsNotificacionBackupSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HQBackupsWsNotificacionBackupSoapPortClient : System.ServiceModel.ClientBase<GetCmdOutput.ServiceReference1.HQBackupsWsNotificacionBackupSoapPort>, GetCmdOutput.ServiceReference1.HQBackupsWsNotificacionBackupSoapPort {
        
        public HQBackupsWsNotificacionBackupSoapPortClient() {
        }
        
        public HQBackupsWsNotificacionBackupSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HQBackupsWsNotificacionBackupSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HQBackupsWsNotificacionBackupSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HQBackupsWsNotificacionBackupSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetCmdOutput.ServiceReference1.ExecuteResponse GetCmdOutput.ServiceReference1.HQBackupsWsNotificacionBackupSoapPort.Execute(GetCmdOutput.ServiceReference1.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public string Execute(GetCmdOutput.ServiceReference1.SdtBackup Sdtbackup) {
            GetCmdOutput.ServiceReference1.ExecuteRequest inValue = new GetCmdOutput.ServiceReference1.ExecuteRequest();
            inValue.Sdtbackup = Sdtbackup;
            GetCmdOutput.ServiceReference1.ExecuteResponse retVal = ((GetCmdOutput.ServiceReference1.HQBackupsWsNotificacionBackupSoapPort)(this)).Execute(inValue);
            return retVal.retval;
        }
    }
}
