


ALTER TABLE [dbo].[CNT_PUC]  WITH CHECK ADD  CONSTRAINT [ICNT_PUC1] FOREIGN KEY([PucAnoCod], [PucPucCod])
REFERENCES [dbo].[CNT_PUC] ([AnoCod], [PucCod]);
GO

ALTER TABLE [dbo].[CNT_PUC] CHECK CONSTRAINT [ICNT_PUC1];
GO


GO

ALTER TABLE [dbo].[CNT_SaldoInicial]  WITH CHECK ADD  CONSTRAINT [ICNT_SALDOINICIAL] FOREIGN KEY([SdoCenCod])
REFERENCES [dbo].[CNT_CentroCosto] ([CenCod])
GO

ALTER TABLE [dbo].[CNT_SaldoInicial] CHECK CONSTRAINT [ICNT_SALDOINICIAL]
GO


GO

ALTER TABLE [dbo].[CNT_SaldoInicial]  WITH CHECK ADD  CONSTRAINT [GX_0022001R] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[CNT_SaldoInicial] CHECK CONSTRAINT [GX_0022001R]
GO



GO

ALTER TABLE [dbo].[CNT_SaldoInicial]  WITH CHECK ADD  CONSTRAINT [ICNT_SALDOINICIAL] FOREIGN KEY([SdoCenCod])
REFERENCES [dbo].[CNT_CentroCosto] ([CenCod])
GO

ALTER TABLE [dbo].[CNT_SaldoInicial] CHECK CONSTRAINT [ICNT_SALDOINICIAL]
GO




GO

ALTER TABLE [dbo].[CNT_SaldoInicial]  WITH CHECK ADD  CONSTRAINT [GX_0022001R] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[CNT_SaldoInicial] CHECK CONSTRAINT [GX_0022001R]
GO



GO

ALTER TABLE [dbo].[GRL_CargueAsiento]  WITH CHECK ADD  CONSTRAINT [GX_0053001R] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[GRL_CargueAsiento] CHECK CONSTRAINT [GX_0053001R]
GO




GO

ALTER TABLE [dbo].[PPA_CXPDet]  WITH CHECK ADD  CONSTRAINT [ICUENTASXPAGARDETALLE1] FOREIGN KEY([FueCod])
REFERENCES [dbo].[PPT_Fuente] ([FueCod])
GO

ALTER TABLE [dbo].[PPA_CXPDet] CHECK CONSTRAINT [ICUENTASXPAGARDETALLE1]
GO



GO

ALTER TABLE [dbo].[PPA_CXPDet]  WITH CHECK ADD  CONSTRAINT [ICUENTASXPAGARDETALLE2] FOREIGN KEY([AnoCod], [PptaCod])
REFERENCES [dbo].[PPA_Rubro] ([AnoCod], [PptaCod])
GO

ALTER TABLE [dbo].[PPA_CXPDet] CHECK CONSTRAINT [ICUENTASXPAGARDETALLE2]
GO




GO

ALTER TABLE [dbo].[PPA_CXPDet]  WITH CHECK ADD  CONSTRAINT [ICUENTASXPAGARDETALLE3] FOREIGN KEY([AnoCod], [CxpCod])
REFERENCES [dbo].[PPA_CXP] ([AnoCod], [CxpCod])
GO

ALTER TABLE [dbo].[PPA_CXPDet] CHECK CONSTRAINT [ICUENTASXPAGARDETALLE3]
GO




GO

ALTER TABLE [dbo].[PPG_Modificacion]  WITH CHECK ADD  CONSTRAINT [GX_000V001R] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[PPG_Modificacion] CHECK CONSTRAINT [GX_000V001R]
GO



GO

ALTER TABLE [dbo].[PPG_Rubro]  WITH CHECK ADD  CONSTRAINT [GX_000Q001R] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[PPG_Rubro] CHECK CONSTRAINT [GX_000Q001R]
GO



GO

ALTER TABLE [dbo].[PPI_Modificacion]  WITH CHECK ADD  CONSTRAINT [GX_001A001R] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[PPI_Modificacion] CHECK CONSTRAINT [GX_001A001R]
GO



ALTER TABLE [dbo].[PPI_Rubro]  WITH CHECK ADD  CONSTRAINT [IPPI_RUBRO] FOREIGN KEY([CtaIEntCod])
REFERENCES [dbo].[GRL_Entidad] ([EntCod])
GO

ALTER TABLE [dbo].[PPI_Rubro] CHECK CONSTRAINT [IPPI_RUBRO]
GO



GO

ALTER TABLE [dbo].[REN_CGNSaldoInicial]  WITH CHECK ADD  CONSTRAINT [IREN_CGNSALDOINICIAL] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[REN_CGNSaldoInicial] CHECK CONSTRAINT [IREN_CGNSALDOINICIAL]
GO



GO

ALTER TABLE [dbo].[TES_Consignacion]  WITH CHECK ADD  CONSTRAINT [ICONSIGNACION1] FOREIGN KEY([ConOriCueCod])
REFERENCES [dbo].[TES_CuentaBancaria] ([CueCod])
GO

ALTER TABLE [dbo].[TES_Consignacion] CHECK CONSTRAINT [ICONSIGNACION1]
GO




GO

ALTER TABLE [dbo].[TES_Consignacion]  WITH CHECK ADD  CONSTRAINT [ICONSIGNACION2] FOREIGN KEY([ConDestCueCod])
REFERENCES [dbo].[TES_CuentaBancaria] ([CueCod])
GO

ALTER TABLE [dbo].[TES_Consignacion] CHECK CONSTRAINT [ICONSIGNACION2]
GO



GO

ALTER TABLE [dbo].[TES_CXC]  WITH CHECK ADD  CONSTRAINT [ITES_CXC3] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[TES_CXC] CHECK CONSTRAINT [ITES_CXC3]
GO





GO

ALTER TABLE [dbo].[TES_Deduccion]  WITH CHECK ADD  CONSTRAINT [GX_000O001R] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[TES_Deduccion] CHECK CONSTRAINT [GX_000O001R]
GO





GO

ALTER TABLE [dbo].[TES_Imputacion]  WITH CHECK ADD  CONSTRAINT [ITES_IMPUTACION] FOREIGN KEY([RecaCenCod])
REFERENCES [dbo].[CNT_CentroCosto] ([CenCod])
GO

ALTER TABLE [dbo].[TES_Imputacion] CHECK CONSTRAINT [ITES_IMPUTACION]
GO






GO

ALTER TABLE [dbo].[TES_Imputacion]  WITH CHECK ADD  CONSTRAINT [ITES_IMPUTACION1] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[TES_Imputacion] CHECK CONSTRAINT [ITES_IMPUTACION1]
GO





GO

ALTER TABLE [dbo].[TES_LoteCargue]  WITH CHECK ADD  CONSTRAINT [IGRL_LOTECARGUE] FOREIGN KEY([AnoCod], [TipCgeCod])
REFERENCES [dbo].[TES_HomCargue] ([AnoCod], [TipCgeCod])
GO

ALTER TABLE [dbo].[TES_LoteCargue] CHECK CONSTRAINT [IGRL_LOTECARGUE]
GO




GO

ALTER TABLE [dbo].[TES_ObligacionDet]  WITH CHECK ADD  CONSTRAINT [GX_000H001X001R] FOREIGN KEY([AnoCod], [PagCod])
REFERENCES [dbo].[PPG_OP] ([AnoCod], [PagCod])
GO

ALTER TABLE [dbo].[TES_ObligacionDet] CHECK CONSTRAINT [GX_000H001X001R]
GO




GO

ALTER TABLE [dbo].[TES_ObligacionDet]  WITH CHECK ADD  CONSTRAINT [GX_000H0020001R] FOREIGN KEY([AnoCod], [OprCod])
REFERENCES [dbo].[PPA_OP] ([AnoCod], [OprCod])
GO

ALTER TABLE [dbo].[TES_ObligacionDet] CHECK CONSTRAINT [GX_000H0020001R]
GO




GO

ALTER TABLE [dbo].[TES_ObligacionDet]  WITH CHECK ADD  CONSTRAINT [GX_000H0022001R] FOREIGN KEY([AnoCod], [CxpCod])
REFERENCES [dbo].[PPA_CXP] ([AnoCod], [CxpCod])
GO

ALTER TABLE [dbo].[TES_ObligacionDet] CHECK CONSTRAINT [GX_000H0022001R]
GO





GO

ALTER TABLE [dbo].[TES_ObligacionDet]  WITH CHECK ADD  CONSTRAINT [ITES_OBLIGACIONDET] FOREIGN KEY([AnoCod], [OblRetCod])
REFERENCES [dbo].[TES_Retencion] ([AnoCod], [RetCod])
GO

ALTER TABLE [dbo].[TES_ObligacionDet] CHECK CONSTRAINT [ITES_OBLIGACIONDET]
GO





GO

ALTER TABLE [dbo].[TES_Cheque]  WITH CHECK ADD  CONSTRAINT [ICHEQUE4] FOREIGN KEY([AnoCod], [CheFieCod])
REFERENCES [dbo].[TES_PagoRecaudo] ([AnoCod], [FieCod])
GO

ALTER TABLE [dbo].[TES_Cheque] CHECK CONSTRAINT [ICHEQUE4]
GO




GO

ALTER TABLE [dbo].[TES_ConceptoImputable]  WITH CHECK ADD  CONSTRAINT [ITES_CONCEPTOINGRESO] FOREIGN KEY([AnoCod], [CcpCtaICod], [CcpFueCod])
REFERENCES [dbo].[PPI_Presupuesto] ([AnoCod], [CtaICod], [FueCod])
GO

ALTER TABLE [dbo].[TES_ConceptoImputable] CHECK CONSTRAINT [ITES_CONCEPTOINGRESO]
GO








GO

ALTER TABLE [dbo].[TES_Consignacion]  WITH CHECK ADD  CONSTRAINT [ITES_CONSIGNACION1] FOREIGN KEY([ConCenCod])
REFERENCES [dbo].[CNT_CentroCosto] ([CenCod])
GO

ALTER TABLE [dbo].[TES_Consignacion] CHECK CONSTRAINT [ITES_CONSIGNACION1]
GO





GO

ALTER TABLE [dbo].[TES_Consignacion]  WITH CHECK ADD  CONSTRAINT [ITES_CONSIGNACION2] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[TES_Consignacion] CHECK CONSTRAINT [ITES_CONSIGNACION2]
GO




GO

ALTER TABLE [dbo].[TES_LoteCargue]  WITH CHECK ADD  CONSTRAINT [ITES_LOTECARGUE] FOREIGN KEY([CgeCenCod])
REFERENCES [dbo].[CNT_CentroCosto] ([CenCod])
GO

ALTER TABLE [dbo].[TES_LoteCargue] CHECK CONSTRAINT [ITES_LOTECARGUE]
GO





GO

ALTER TABLE [dbo].[TES_PagoRecaudo]  WITH CHECK ADD  CONSTRAINT [IINGRESOSEGRESOS1] FOREIGN KEY([CueCod])
REFERENCES [dbo].[TES_CuentaBancaria] ([CueCod])
GO

ALTER TABLE [dbo].[TES_PagoRecaudo] CHECK CONSTRAINT [IINGRESOSEGRESOS1]
GO




GO

ALTER TABLE [dbo].[TES_PagoRecaudo]  WITH CHECK ADD  CONSTRAINT [ITES_INGRESOSEGRESOS] FOREIGN KEY([MepCod])
REFERENCES [dbo].[TES_MedioPago] ([MepCod])
GO

ALTER TABLE [dbo].[TES_PagoRecaudo] CHECK CONSTRAINT [ITES_INGRESOSEGRESOS]
GO





GO

ALTER TABLE [dbo].[TES_PagoRecaudo]  WITH CHECK ADD  CONSTRAINT [ITES_PAGORECAUDO] FOREIGN KEY([FieTerCod])
REFERENCES [dbo].[GRL_Tercero] ([TerCod])
GO

ALTER TABLE [dbo].[TES_PagoRecaudo] CHECK CONSTRAINT [ITES_PAGORECAUDO]
GO





GO

ALTER TABLE [dbo].[TES_PagoRecaudo]  WITH CHECK ADD  CONSTRAINT [ITES_PAGORECAUDO1] FOREIGN KEY([FieEntCod])
REFERENCES [dbo].[GRL_Entidad] ([EntCod])
GO

ALTER TABLE [dbo].[TES_PagoRecaudo] CHECK CONSTRAINT [ITES_PAGORECAUDO1]
GO




GO

ALTER TABLE [dbo].[TES_PagoRecaudo]  WITH CHECK ADD  CONSTRAINT [ITES_PAGORECAUDO2] FOREIGN KEY([FieCenCod])
REFERENCES [dbo].[CNT_CentroCosto] ([CenCod])
GO

ALTER TABLE [dbo].[TES_PagoRecaudo] CHECK CONSTRAINT [ITES_PAGORECAUDO2]
GO






GO

ALTER TABLE [dbo].[TES_PagoRecaudo]  WITH CHECK ADD  CONSTRAINT [ITES_PAGORECAUDO3] FOREIGN KEY([FieFirTes])
REFERENCES [dbo].[GRL_Tercero] ([TerCod])
GO

ALTER TABLE [dbo].[TES_PagoRecaudo] CHECK CONSTRAINT [ITES_PAGORECAUDO3]
GO






GO

ALTER TABLE [dbo].[TES_PagoRecaudo]  WITH CHECK ADD  CONSTRAINT [ITES_PAGORECAUDO4] FOREIGN KEY([FieFirTesAux])
REFERENCES [dbo].[GRL_Tercero] ([TerCod])
GO

ALTER TABLE [dbo].[TES_PagoRecaudo] CHECK CONSTRAINT [ITES_PAGORECAUDO4]
GO





GO

ALTER TABLE [dbo].[TES_PagoRecaudo]  WITH CHECK ADD  CONSTRAINT [ITES_PAGORECAUDO5] FOREIGN KEY([FieFirTesHaci])
REFERENCES [dbo].[GRL_Tercero] ([TerCod])
GO

ALTER TABLE [dbo].[TES_PagoRecaudo] CHECK CONSTRAINT [ITES_PAGORECAUDO5]
GO





GO

ALTER TABLE [dbo].[TES_PagoRecaudo]  WITH CHECK ADD  CONSTRAINT [ITES_PAGORECAUDO6] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[TES_PagoRecaudo] CHECK CONSTRAINT [ITES_PAGORECAUDO6]
GO





GO

ALTER TABLE [dbo].[TES_PagoRecaudoIng]  WITH CHECK ADD  CONSTRAINT [ITES_PAGORECAUDOING] FOREIGN KEY([AnoCod], [CcpCod])
REFERENCES [dbo].[TES_ConceptoImputable] ([AnoCod], [CcpCod])
GO

ALTER TABLE [dbo].[TES_PagoRecaudoIng] CHECK CONSTRAINT [ITES_PAGORECAUDOING]
GO






GO

ALTER TABLE [dbo].[TES_PagoRecaudoObl]  WITH CHECK ADD  CONSTRAINT [IINGRESOSEGRESOSOBLIGACIONES2] FOREIGN KEY([AnoCod], [FieCod])
REFERENCES [dbo].[TES_PagoRecaudo] ([AnoCod], [FieCod])
GO

ALTER TABLE [dbo].[TES_PagoRecaudoObl] CHECK CONSTRAINT [IINGRESOSEGRESOSOBLIGACIONES2]
GO




GO

ALTER TABLE [dbo].[TES_Retencion]  WITH CHECK ADD  CONSTRAINT [ITES_RETENCION2] FOREIGN KEY([RetCenCod])
REFERENCES [dbo].[CNT_CentroCosto] ([CenCod])
GO

ALTER TABLE [dbo].[TES_Retencion] CHECK CONSTRAINT [ITES_RETENCION2]
GO






GO

ALTER TABLE [dbo].[TES_Traslado]  WITH CHECK ADD  CONSTRAINT [ITES_TRASLADO2] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[TES_Traslado] CHECK CONSTRAINT [ITES_TRASLADO2]
GO





GO

ALTER TABLE [dbo].[CCB_Conciliacion]  WITH CHECK ADD  CONSTRAINT [GX_0051001R] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[CCB_Conciliacion] CHECK CONSTRAINT [GX_0051001R]
GO




GO

ALTER TABLE [dbo].[CCB_ConciliacionDet]  WITH CHECK ADD  CONSTRAINT [GX_005201PC001R] FOREIGN KEY([AnoCod], [CcbDetExtbCod])
REFERENCES [dbo].[CCB_Extracto] ([AnoCod], [ExtbCod])
GO

ALTER TABLE [dbo].[CCB_ConciliacionDet] CHECK CONSTRAINT [GX_005201PC001R]
GO





ALTER TABLE [dbo].[CNT_CierreContable] ALTER COLUMN [CenTerCod] DECIMAL (15,0); 


GO

ALTER TABLE [dbo].[CNT_CierreContable]  WITH CHECK ADD  CONSTRAINT [ICNT_CIERRECONTABLE3] FOREIGN KEY([CenTerCod])
REFERENCES [dbo].[GRL_Tercero] ([TerCod])
GO

ALTER TABLE [dbo].[CNT_CierreContable] CHECK CONSTRAINT [ICNT_CIERRECONTABLE3]
GO






GO

ALTER TABLE [dbo].[GRL_CargueAsiento]  WITH CHECK ADD  CONSTRAINT [GX_0053001R] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[GRL_CargueAsiento] CHECK CONSTRAINT [GX_0053001R]
GO





GO

ALTER TABLE [dbo].[GRL_CargueCDP]  WITH CHECK ADD  CONSTRAINT [GX_004F001R] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[GRL_CargueCDP] CHECK CONSTRAINT [GX_004F001R]
GO





GO

ALTER TABLE [dbo].[GRL_CargueDeduccionObl]  WITH CHECK ADD  CONSTRAINT [GX_0055001R] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[GRL_CargueDeduccionObl] CHECK CONSTRAINT [GX_0055001R]
GO






GO

ALTER TABLE [dbo].[GRL_CargueOPR]  WITH CHECK ADD  CONSTRAINT [GX_004L001R] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[GRL_CargueOPR] CHECK CONSTRAINT [GX_004L001R]
GO





GO

ALTER TABLE [dbo].[GRL_CargueOPR]  WITH CHECK ADD  CONSTRAINT [ICARGUEOPR1] FOREIGN KEY([AnoCod], [LcgCod])
REFERENCES [dbo].[GRL_LoteInformacion] ([AnoCod], [LcgCod])
GO

ALTER TABLE [dbo].[GRL_CargueOPR] CHECK CONSTRAINT [ICARGUEOPR1]
GO




GO

ALTER TABLE [dbo].[GRL_CarguePptoGasto]  WITH CHECK ADD  CONSTRAINT [IGRL_CARGUEPPTOGASTO] FOREIGN KEY([AnoCod], [LcgCod])
REFERENCES [dbo].[GRL_LoteInformacion] ([AnoCod], [LcgCod])
GO

ALTER TABLE [dbo].[GRL_CarguePptoGasto] CHECK CONSTRAINT [IGRL_CARGUEPPTOGASTO]
GO




GO

ALTER TABLE [dbo].[GRL_CarguePptoIngreso]  WITH CHECK ADD  CONSTRAINT [IGRL_CARGUEPPTOINGRESO] FOREIGN KEY([AnoCod], [LcgCod])
REFERENCES [dbo].[GRL_LoteInformacion] ([AnoCod], [LcgCod])
GO

ALTER TABLE [dbo].[GRL_CarguePptoIngreso] CHECK CONSTRAINT [IGRL_CARGUEPPTOINGRESO]
GO




GO

ALTER TABLE [dbo].[GRL_CarguePuc]  WITH CHECK ADD  CONSTRAINT [IGRL_CARGUEPUC] FOREIGN KEY([AnoCod], [LcgCod])
REFERENCES [dbo].[GRL_LoteInformacion] ([AnoCod], [LcgCod])
GO

ALTER TABLE [dbo].[GRL_CarguePuc] CHECK CONSTRAINT [IGRL_CARGUEPUC]
GO




GO

ALTER TABLE [dbo].[GRL_CargueRP]  WITH CHECK ADD  CONSTRAINT [GX_004G001R] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[GRL_CargueRP] CHECK CONSTRAINT [GX_004G001R]
GO





GO

ALTER TABLE [dbo].[GRL_CargueSdoIni]  WITH CHECK ADD  CONSTRAINT [GX_0054001R] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[GRL_CargueSdoIni] CHECK CONSTRAINT [GX_0054001R]
GO





GO

ALTER TABLE [dbo].[GRL_CargueTercero]  WITH CHECK ADD  CONSTRAINT [IGRL_CARGUETERCERO] FOREIGN KEY([AnoCod], [LcgCod])
REFERENCES [dbo].[GRL_LoteInformacion] ([AnoCod], [LcgCod])
GO

ALTER TABLE [dbo].[GRL_CargueTercero] CHECK CONSTRAINT [IGRL_CARGUETERCERO]
GO






GO

ALTER TABLE [dbo].[GRL_LoteInformacion]  WITH CHECK ADD  CONSTRAINT [ILOTECARGUE2] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[GRL_LoteInformacion] CHECK CONSTRAINT [ILOTECARGUE2]
GO





GO

ALTER TABLE [dbo].[PPG_SolicitudCDP]  WITH CHECK ADD  CONSTRAINT [IPPG_SOLICITUDCDP4] FOREIGN KEY([ScdpOrdCod])
REFERENCES [dbo].[GRL_Tercero] ([TerCod])
GO

ALTER TABLE [dbo].[PPG_SolicitudCDP] CHECK CONSTRAINT [IPPG_SOLICITUDCDP4]
GO







GO

ALTER TABLE [dbo].[PPI_Rubro]  WITH CHECK ADD  CONSTRAINT [GX_0018001R] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[PPI_Rubro] CHECK CONSTRAINT [GX_0018001R]
GO






GO

ALTER TABLE [dbo].[GRL_CargueAsiento]  WITH CHECK ADD  CONSTRAINT [GX_0053001R] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[GRL_CargueAsiento] CHECK CONSTRAINT [GX_0053001R]
GO





GO

ALTER TABLE [dbo].[CNT_Comprobante]  WITH CHECK ADD  CONSTRAINT [ICNT_COMPROBANTE4] FOREIGN KEY([AnoCod])
REFERENCES [dbo].[GRL_Ano] ([AnoCod])
GO

ALTER TABLE [dbo].[CNT_Comprobante] CHECK CONSTRAINT [ICNT_COMPROBANTE4]
GO



GO

ALTER TABLE [dbo].[CNT_ComprobanteDet]  WITH CHECK ADD  CONSTRAINT [ICNT_COMPROBANTEDET] FOREIGN KEY([AsiDetAno], [PucCod])
REFERENCES [dbo].[CNT_PUC] ([AnoCod], [PucCod])
GO

ALTER TABLE [dbo].[CNT_ComprobanteDet] CHECK CONSTRAINT [ICNT_COMPROBANTEDET]
GO




GO

ALTER TABLE [dbo].[CNT_ComprobanteDet]  WITH CHECK ADD  CONSTRAINT [ICNT_COMPROBANTEDET1] FOREIGN KEY([AsiDetAno], [AsiCod])
REFERENCES [dbo].[CNT_Comprobante] ([AnoCod], [AsiCod])
GO

ALTER TABLE [dbo].[CNT_ComprobanteDet] CHECK CONSTRAINT [ICNT_COMPROBANTEDET1]
GO





GO

ALTER TABLE [dbo].[PPG_HomologacionConpes]  WITH CHECK ADD  CONSTRAINT [IPPG_HOMOLOGACIONCONPES] FOREIGN KEY([ConpHomoFue])
REFERENCES [dbo].[PPT_Fuente] ([FueCod])
GO

ALTER TABLE [dbo].[PPG_HomologacionConpes] CHECK CONSTRAINT [IPPG_HOMOLOGACIONCONPES]
GO








