//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoreBakResult.Restore {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SdtRestore", Namespace="CS3HQ")]
    [System.SerializableAttribute()]
    public partial class SdtRestore : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BckNomField;
        
        private bool BckEstField;
        
        private string BckMsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string BckNom {
            get {
                return this.BckNomField;
            }
            set {
                if ((object.ReferenceEquals(this.BckNomField, value) != true)) {
                    this.BckNomField = value;
                    this.RaisePropertyChanged("BckNom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool BckEst {
            get {
                return this.BckEstField;
            }
            set {
                if ((this.BckEstField.Equals(value) != true)) {
                    this.BckEstField = value;
                    this.RaisePropertyChanged("BckEst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string BckMsg {
            get {
                return this.BckMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.BckMsgField, value) != true)) {
                    this.BckMsgField = value;
                    this.RaisePropertyChanged("BckMsg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="HQ.Backups.WsRestoreBackupSoapPort", Namespace="CS3HQ", ConfigurationName="Restore.HQBackupsWsRestoreBackupSoapPort")]
    public interface HQBackupsWsRestoreBackupSoapPort {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (HQ.Backups.WsRestoreBackup.Execute) del mensaje ExecuteRequest no coincide con el valor predeterminado (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="CS3HQaction/hq.backups.AWSRESTOREBACKUP.Execute", ReplyAction="*")]
        RestoreBakResult.Restore.ExecuteResponse Execute(RestoreBakResult.Restore.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HQ.Backups.WsRestoreBackup.Execute", WrapperNamespace="CS3HQ", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS3HQ", Order=0)]
        public RestoreBakResult.Restore.SdtRestore Sdtrestore;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(RestoreBakResult.Restore.SdtRestore Sdtrestore) {
            this.Sdtrestore = Sdtrestore;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HQ.Backups.WsRestoreBackup.ExecuteResponse", WrapperNamespace="CS3HQ", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS3HQ", Order=0)]
        public string retval;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(string retval) {
            this.retval = retval;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HQBackupsWsRestoreBackupSoapPortChannel : RestoreBakResult.Restore.HQBackupsWsRestoreBackupSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HQBackupsWsRestoreBackupSoapPortClient : System.ServiceModel.ClientBase<RestoreBakResult.Restore.HQBackupsWsRestoreBackupSoapPort>, RestoreBakResult.Restore.HQBackupsWsRestoreBackupSoapPort {
        
        public HQBackupsWsRestoreBackupSoapPortClient() {
        }
        
        public HQBackupsWsRestoreBackupSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HQBackupsWsRestoreBackupSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HQBackupsWsRestoreBackupSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HQBackupsWsRestoreBackupSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestoreBakResult.Restore.ExecuteResponse RestoreBakResult.Restore.HQBackupsWsRestoreBackupSoapPort.Execute(RestoreBakResult.Restore.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public string Execute(RestoreBakResult.Restore.SdtRestore Sdtrestore) {
            RestoreBakResult.Restore.ExecuteRequest inValue = new RestoreBakResult.Restore.ExecuteRequest();
            inValue.Sdtrestore = Sdtrestore;
            RestoreBakResult.Restore.ExecuteResponse retVal = ((RestoreBakResult.Restore.HQBackupsWsRestoreBackupSoapPort)(this)).Execute(inValue);
            return retVal.retval;
        }
    }
}
