@ECHO OFF
cd C:\Users\daiber\Desktop\CONTINGENCIA\
SET RUTABACKUPS=C:\S3\ 								
SET BASEDEDATOS=PTributario_SantoTomas
SET RUTAREORG="C:\Program Files (x86)\Artech\GeneXus\"		
SET RUTAFIN=C:\S3\SWIT\										
SET USUARIO=AlcBaranoa
SET CLAVE=123
SET IPFTP=go.comercializadora-s3.com
SET PUERTO=21
SET TIPO=SWIT
CALL BACKUP.bat %RUTABACKUPS% %BASEDEDATOS% %RUTAREORG% %RUTAFIN% %USUARIO% %CLAVE% %IPFTP% %TIPO% %PUERTO%
@ECHO ON